name: Build and Push Heavy Docker Image

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Hapus software bawaan runner (Android, .NET, Haskell, dll)
      - name: Maximize Build Space
        uses: easimon/maximize-build-space@v10
        with:
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'
          root-reserve-mb: 2048
          swap-size-mb: 1024

      # 2. Sapu bersih sisa toolchain bawaan untuk ruang maksimal (~40GB+)
      - name: Free Disk Space (Extra Cleanup)
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/share/boost
          sudo apt-get clean
          df -h

      # 3. Checkout Kode Project
      - name: Checkout Code
        uses: actions/checkout@v4

      # 4. Login ke Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 5. Build & Push Image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: sujinwo555/movie-recap:v1
